GET http://localhost:3000/api/user
###

POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "username":"abebe3",
    "email":"abebe3@gmail.com",
    "password":"12345"
}